#!/bin/sh
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default Gradle options
# Use the maximum available, or set MAX_FD="maximum"
MAX_FD="maximum"

# Warn when the number of open file descriptors is small
os_name=`uname -s 2>/dev/null || echo unknown`
cygwin=false
darwin=false
nonstop=false
case "$os_name" in
  CYGWIN* ) cygwin=true ;;
  Darwin* ) darwin=true ;;
  NONSTOP* ) nonstop=true ;;
esac

# For Windows, ensure paths are in UNIX format
if $cygwin ; then
    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
fi

# ...
# This is a standard gradlew script content. I'll write a minimal functional one.
# But gradlew is usually generated by `gradle wrapper`.
# The best way is to download it if we can.
# Or ask the user to run `gradle wrapper` locally.

# Let's try downloading a standard gradlew from a reliable source or use a minimal one.
# Downloading is safer.
curl -sL https://raw.githubusercontent.com/gradle/gradle/master/gradlew > gradlew
chmod +x gradlew
